[phases.setup]
cmds = [
  "apt-get update -y || (sleep 10 && apt-get update -y)",
  "apt-get install -y --no-install-recommends libasound2t64 libatk1.0-0 libatk-bridge2.0-0 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxss1 libxtst6 fonts-liberation"
]

[start]
cmd = "npm start"
